### ISSUE TITLE
Churn requires a bazaar, git, mercurial, or subversion source control (RuntimeError)

### ISSUE THREAD

**Issue by vovanmozg** [danmayer/churn#58]
Hello, 
I install gem metric_fu, but it breaking on Churn executing. I try start only churn, but executing breaking also:
```
www@devos:~/rails_apps/f220_dev_app$ churn
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/churn-0.0.35/lib
F, [2015-10-01T02:37:34.030169 #17227] FATAL -- : Churn requires a bazaar, git, mercurial, or subversion source control (RuntimeError)
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/churn-0.0.35/lib/churn/scm/source_control.rb:16:in `set_source_control'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/churn-0.0.35/lib/churn/calculator.rb:35:in `initialize'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/churn-0.0.35/bin/churn:74:in `new'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/churn-0.0.35/bin/churn:74:in `report_churn'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/churn-0.0.35/bin/churn:82:in `run'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/main-6.1.0/lib/main/program/class_methods.rb:156:in `block in run'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/main-6.1.0/lib/main/program/class_methods.rb:145:in `catch'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/main-6.1.0/lib/main/program/class_methods.rb:145:in `run'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/main-6.1.0/lib/main/factories.rb:18:in `run'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/main-6.1.0/lib/main/factories.rb:25:in `Main'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/gems/churn-0.0.35/bin/churn:15:in `<top (required)>'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/bin/churn:23:in `load'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/bin/churn:23:in `<main>'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/bin/ruby_executable_hooks:15:in `eval'
/home/www/.rvm/gems/ruby-2.2.0@rails420_f220_app/bin/ruby_executable_hooks:15:in `<main>'
www@devos:~/rails_apps/f220_dev_app$
```

I have git installed on my environment

**Comment by vovanmozg** [comment]
Sorry, i hadn't installed git in project directory :(
