### ISSUE TITLE
Invalid byte sequence in UTF-8

### ISSUE THREAD

**Issue by RedaBenh** [danmayer/churn#64]
When i run 

`churn -y `

In my project i get the following issue:

```
F, [2016-10-06T00:03:13.033320 #28182] FATAL -- : invalid byte sequence in UTF-8 (ArgumentError)
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/lib/churn/scm/git_analyzer.rb:11:in 'split'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/lib/churn/scm/git_analyzer.rb:11:in 'get_logs'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/lib/churn/calculator.rb:253:in 'parse_log_for_changes'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/lib/churn/calculator.rb:84:in 'emit'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/lib/churn/calculator.rb:55:in 'report'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/bin/churn:73:in 'report_churn'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/bin/churn:81:in 'run'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/main-6.2.0/lib/main/program/class_methods.rb:156:in 'block in run'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/main-6.2.0/lib/main/program/class_methods.rb:145:in 'catch'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/main-6.2.0/lib/main/program/class_methods.rb:145:in 'run'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/main-6.2.0/lib/main/factories.rb:18:in 'run'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/main-6.2.0/lib/main/factories.rb:25:in 'Main'
/Users/myuser/.rvm/gems/ruby-2.1.8/gems/churn-1.0.2/bin/churn:14:in '<top (required)>'
/Users/myuser/.rvm/gems/ruby-2.1.8/bin/churn:23:in 'load'
/Users/myuser/.rvm/gems/ruby-2.1.8/bin/churn:23:in '<main>'
/Users/myuser/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in 'eval'
/Users/myuser/.rvm/gems/ruby-2.1.8/bin/ruby_executable_hooks:15:in '<main>'

```

There is any way to fix this encoding issue ?

**Comment by danmayer** [comment]
hmm sorry I would need more details to figure out what is going on here. Do you know the text or file it was crashing on... Seems like a line in your git logs. If you could track that down I could likely fix.
